### ISSUE TITLE
Link isn't available anymore.

### ISSUE THREAD

**Issue by Link1503** [AnalogFeelings/analogfeelings.github.io#12]
The URL "https://witchdagger.com/" which is referenced [here](https://github.com/AnalogFeelings/analogfeelings.github.io/blob/92aeb29be6ed834a0fe2e21adb012c30f92a9b43/elements/sidebar.html#L75) in a sidebar element. is not available anymore. Therefore it would be beneficial to either remove or replace the url and the prior image of it.

Kind regards 
Julia :)

![Screenshot of said element](https://github.com/AnalogFeelings/analogfeelings.github.io/assets/104648877/bd40835a-fc89-4e32-8ff0-efb5e405c074)

**Comment by witchdaggah** [comment]
its down temporarily :<
